### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by darkdarcool** [ReplAPI-it/ReplAPI.it-C#1]
how do you make a package in c? lol

**Comment by zghwi** [comment]
it won't be a package, it will be a C header
if you have some knowledge in C... you'll understand, but if not, here is an explanation for a [Header](https://www.tutorialspoint.com/cprogramming/c_header_files.htm)

**Comment by darkdarcool** [comment]
ah ok, I know what h files are, but I thought a packager system would be involved for some reason.

**Comment by whippingdot** [comment]
C++

PLS

Also, ya headers are pretty common knowledge, you should know them...

**Comment by darkdarcool** [comment]
I know what h files are,

**Comment by AmazingMech2418** [comment]
> it won't be a package, it will be a C header
> if you have some knowledge in C... you'll understand, but if not, here is an explanation for a [Header](https://www.tutorialspoint.com/cprogramming/c_header_files.htm)

Actually, it will be a package through [Conan](https://conan.io).

**Comment by darkdarcool** [comment]
I knew it would be a packager!

**Comment by darkdarcool** [comment]
also if you need a little help with getting the data, use the official [graphql C++](https://github.com/graphql/libgraphqlparser/) tool.
